/**
 * Copyright (c) IWFDK contributors.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { readFileSync } from 'node:fs';
import {
  Group,
  Object3D,
  PerspectiveCamera,
  Quaternion,
  Scene,
  Vector3,
} from 'three';
import { afterEach, describe, expect, it } from 'vitest';
import {
  FrameControllerVisual,
  frameProfileWithModels,
  loadFrameControllerModels,
  parseFrameControllerModels,
  type FrameControllerModels,
  type FramePose,
} from '../src/frame/models.js';
import {
  loadInputProfile,
  registerInputProfile,
} from '../src/gamepad/input-profiles.js';
import { VALVE_FRAME_PROFILE } from '../src/gamepad/profiles/valve-frame.js';
import { XRControllerVisualAdapter } from '../src/visual/adapter/controller-visual-adapter.js';
import { AnimatedController } from '../src/visual/impl/animated-controller.js';
import type { XRAssetLoader } from '../src/xr-input-manager.js';

// Generated by tools/frame-models (cargo test with UPDATE_FIXTURES=1) from a
// synthetic controller: the trigger rotates 20° about x, the stick tilts 15°
// per axis, A sinks 2.5 mm, a dot shows on A touch, the body never moves.
const FIXTURE = JSON.parse(
  readFileSync(
    new URL('./fixtures/frame-controller-models.json', import.meta.url),
    'utf8',
  ),
) as FrameControllerModels;

const NODE_NAMES = ['trigger', 'stick', 'button_a', 'a_touch_dot', 'body'];

function asset(): Group {
  const scene = new Group();
  for (const name of NODE_NAMES) {
    const node = new Object3D();
    node.name = name;
    scene.add(node);
  }
  return scene;
}

type Pad = {
  buttons: { pressed: boolean; touched: boolean; value: number }[];
  axes: number[];
};

function pad(): Pad {
  return {
    buttons: Array.from({ length: 10 }, () => ({
      pressed: false,
      touched: false,
      value: 0,
    })),
    axes: [0, 0, 0, 0],
  };
}

function source(handedness: 'left' | 'right', gamepad: Pad = pad()) {
  return {
    profiles: ['valve-frame', 'generic-trigger-squeeze-thumbstick'],
    handedness,
    gamepad,
  } as unknown as XRInputSource;
}

function visual(hand: 'left' | 'right', gamepad: Pad) {
  const profile = frameProfileWithModels(FIXTURE, '/models');
  const v = new FrameControllerVisual(
    new Scene(),
    new PerspectiveCamera(),
    asset(),
    profile.layouts[hand]!,
  );
  v.init();
  v.connect(source(hand, gamepad), true);
  return v;
}

function node(v: FrameControllerVisual, name: string) {
  return v.model.getObjectByName(name)!;
}

function expectPose(o: Object3D, pose: FramePose) {
  expect(o.position.distanceTo(new Vector3(...pose.position))).toBeLessThan(
    1e-5,
  );
  // angleTo goes through acos, which is coarse near zero for float32 input.
  expect(
    o.quaternion.angleTo(new Quaternion(...pose.orientation)),
  ).toBeLessThan(1e-3);
}

function animation(kind: string, nodeName: string) {
  return FIXTURE.hands.right!.animations.find(
    (a) => a.kind === kind && a.node === nodeName,
  ) as any;
}

afterEach(() => {
  registerInputProfile(VALVE_FRAME_PROFILE);
});

describe('frame-controller-models.json', () => {
  it('parses the tool output', () => {
    const models = parseFrameControllerModels(FIXTURE);
    expect(models.hands.right?.asset).toBe('right.glb');
    expect(models.hands.right?.animations.map((a) => a.kind).sort()).toEqual([
      'button',
      'button',
      'stick',
      'visibility',
    ]);
  });

  it('rejects other files and versions', () => {
    expect(() => parseFrameControllerModels({})).toThrow();
    expect(() =>
      parseFrameControllerModels({ ...FIXTURE, version: 99 }),
    ).toThrow(/version 99/);
    expect(() => parseFrameControllerModels({ ...FIXTURE, hands: {} })).toThrow(
      /no controller models/,
    );
  });

  it('builds a valve-frame profile pointing at the models', () => {
    const profile = frameProfileWithModels(FIXTURE, 'https://cdn.test/m/');
    const right = profile.layouts.right as any;
    expect(right.assetPath).toBe('https://cdn.test/m/right.glb');
    expect(right.frameModel).toBe(FIXTURE.hands.right);
    expect(right.components['a-button'].gamepadIndices.button).toBe(4);
    for (const c of Object.values(right.components) as any[]) {
      expect(c.visualResponses).toEqual({});
    }
    expect(profile.profileId).toBe('valve-frame');
  });
});

describe('loadFrameControllerModels', () => {
  it('fetches the models and registers them with their visual', async () => {
    const urls: string[] = [];
    const fetchImpl = (async (url: string) => {
      urls.push(url);
      return { ok: true, json: async () => FIXTURE };
    }) as unknown as typeof fetch;
    await loadFrameControllerModels('/frame-models/', fetchImpl);
    expect(urls).toEqual(['/frame-models/frame-controller-models.json']);

    const config = loadInputProfile(source('right'));
    expect(config.visualClass).toBe(FrameControllerVisual);
    expect(config.assetPath).toBe('/frame-models/right.glb');
  });

  it('reports HTTP errors', async () => {
    const fetchImpl = (async () => ({
      ok: false,
      status: 404,
      statusText: 'Not Found',
    })) as unknown as typeof fetch;
    await expect(loadFrameControllerModels('/x', fetchImpl)).rejects.toThrow(
      /404/,
    );
    expect(loadInputProfile(source('right')).visualClass).toBeUndefined();
  });
});

describe('FrameControllerVisual', () => {
  it('places the model at its grip offset and hides rest-hidden nodes', () => {
    const v = visual('right', pad());
    const inner = v.model.children[0];
    expectPose(inner, FIXTURE.hands.right!.gripFromModel!);
    expect(node(v, 'a_touch_dot').visible).toBe(false);
    expect(node(v, 'body').visible).toBe(true);
  });

  it('replays the trigger, A button and touch dot', () => {
    const gamepad = pad();
    const v = visual('right', gamepad);
    const trigger = animation('button', 'trigger');
    const a = animation('button', 'button_a');

    v.update();
    expectPose(node(v, 'trigger'), trigger.rest);
    expectPose(node(v, 'button_a'), a.rest);

    gamepad.buttons[0].value = 1;
    gamepad.buttons[4] = { pressed: true, touched: true, value: 1 };
    v.update();
    expectPose(node(v, 'trigger'), trigger.pressed);
    expectPose(node(v, 'button_a'), a.pressed);
    expect(node(v, 'a_touch_dot').visible).toBe(true);

    gamepad.buttons[0].value = 0.5;
    v.update();
    const half = node(v, 'trigger').quaternion.angleTo(
      new Quaternion(
        ...(trigger.rest.orientation as [number, number, number, number]),
      ),
    );
    expect(half).toBeGreaterThan(0.15);
    expect(half).toBeLessThan(0.2);
  });

  it('tilts the stick per direction, with gamepad y pointing down', () => {
    const gamepad = pad();
    const v = visual('right', gamepad);
    const stick = animation('stick', 'stick');

    gamepad.axes[2] = 1;
    v.update();
    expectPose(node(v, 'stick'), stick.right);

    gamepad.axes[2] = 0;
    gamepad.axes[3] = -1; // Pushed forward.
    v.update();
    expectPose(node(v, 'stick'), stick.up);

    gamepad.axes[3] = 1;
    v.update();
    expectPose(node(v, 'stick'), stick.down);

    gamepad.axes[3] = 0;
    v.update();
    expectPose(node(v, 'stick'), stick.rest);
  });

  it('skips animations for components the hand does not have', () => {
    const gamepad = pad();
    const v = visual('left', gamepad);
    gamepad.buttons[4] = { pressed: true, touched: true, value: 1 };
    v.update();
    // Slot 4 is D-pad up on the left; the left layout has no a-button, so
    // the node keeps its asset pose.
    expect(node(v, 'button_a').position.length()).toBe(0);
    // Shared components still animate.
    gamepad.buttons[0].value = 1;
    v.update();
    expect(node(v, 'trigger').quaternion.x).toBeGreaterThan(0.17);
  });
});

describe('controller adapter', () => {
  const loader: XRAssetLoader = {
    async loadGLTF() {
      return { scene: asset() } as Awaited<
        ReturnType<XRAssetLoader['loadGLTF']>
      >;
    },
  };

  function adapter() {
    return new XRControllerVisualAdapter(
      new Group(),
      'right',
      true,
      AnimatedController,
      new Scene(),
      new PerspectiveCamera(),
      loader,
    );
  }

  async function settle() {
    await new Promise((resolve) => setTimeout(resolve, 0));
  }

  it('uses the profile visual for Frame controllers', async () => {
    registerInputProfile(frameProfileWithModels(FIXTURE, '/m'), {
      visualClass: FrameControllerVisual as any,
    });
    const a = adapter();
    a.connect(source('right'));
    await settle();
    expect(a.visual).toBeInstanceOf(FrameControllerVisual);
  });

  it('keeps an app-chosen visual', async () => {
    registerInputProfile(frameProfileWithModels(FIXTURE, '/m'), {
      visualClass: FrameControllerVisual as any,
    });
    const a = adapter();
    a.updateVisualImplementation(AnimatedController);
    a.connect(source('right'));
    await settle();
    expect(a.visual).toBeInstanceOf(AnimatedController);
  });
});
