/**
 * Copyright (c) IWFDK contributors.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { readFileSync } from 'node:fs';
import {
  Group,
  Object3D,
  PerspectiveCamera,
  Quaternion,
  Scene,
  Vector3,
} from 'three';
import { afterEach, describe, expect, it } from 'vitest';
import {
  FrameControllerVisual,
  frameEmulationProfileWithModels,
  frameProfileWithModels,
  registerFrameControllerModels,
  loadFrameControllerModels,
  parseFrameControllerModels,
  type FrameControllerModels,
  type FramePose,
} from '../src/frame/models.js';
import {
  DEFAULT_PROFILES_PATH,
  loadInputProfile,
  registerInputProfile,
  unregisterInputProfile,
} from '../src/gamepad/input-profiles.js';
import { VALVE_FRAME_PROFILE } from '../src/gamepad/profiles/valve-frame.js';
import { XRInputVisualAdapter } from '../src/visual/adapter/base-visual-adapter.js';
import { XRControllerVisualAdapter } from '../src/visual/adapter/controller-visual-adapter.js';
import { AnimatedController } from '../src/visual/impl/animated-controller.js';
import type { XRAssetLoader } from '../src/xr-input-manager.js';

// Generated by tools/frame-models (cargo test with UPDATE_FIXTURES=1) from a
// synthetic controller: the trigger rotates 20° about x, the stick tilts 15°
// per axis, A sinks 2.5 mm, a dot shows on A touch, the body never moves.
const FIXTURE = JSON.parse(
  readFileSync(
    new URL('./fixtures/frame-controller-models.json', import.meta.url),
    'utf8',
  ),
) as FrameControllerModels;

const NODE_NAMES = ['trigger', 'stick', 'button_a', 'a_touch_dot', 'body'];

function asset(): Group {
  const scene = new Group();
  for (const name of NODE_NAMES) {
    const node = new Object3D();
    node.name = name;
    scene.add(node);
  }
  return scene;
}

type Pad = {
  buttons: { pressed: boolean; touched: boolean; value: number }[];
  axes: number[];
};

function pad(): Pad {
  return {
    buttons: Array.from({ length: 13 }, () => ({
      pressed: false,
      touched: false,
      value: 0,
    })),
    axes: [0, 0, 0, 0],
  };
}

function source(handedness: 'left' | 'right', gamepad: Pad = pad()) {
  return {
    profiles: ['valve-frame', 'generic-trigger-squeeze-thumbstick'],
    handedness,
    gamepad,
  } as unknown as XRInputSource;
}

function visual(hand: 'left' | 'right', gamepad: Pad) {
  const profile = frameProfileWithModels(FIXTURE);
  const v = new FrameControllerVisual(
    new Scene(),
    new PerspectiveCamera(),
    asset(),
    profile.layouts[hand]!,
  );
  v.init();
  v.connect(source(hand, gamepad), true);
  return v;
}

function node(v: FrameControllerVisual, name: string) {
  return v.model.getObjectByName(name)!;
}

function expectPose(o: Object3D, pose: FramePose) {
  expect(o.position.distanceTo(new Vector3(...pose.position))).toBeLessThan(
    1e-5,
  );
  // angleTo goes through acos, which is coarse near zero for float32 input.
  expect(
    o.quaternion.angleTo(new Quaternion(...pose.orientation)),
  ).toBeLessThan(1e-3);
}

function animation(kind: string, nodeName: string) {
  return FIXTURE.hands.right!.animations.find(
    (a) => a.kind === kind && a.node === nodeName,
  ) as any;
}

afterEach(() => {
  registerInputProfile(VALVE_FRAME_PROFILE);
  unregisterInputProfile('oculus-touch');
  XRInputVisualAdapter.visualCache.clear();
});

describe('frame-controller-models.json', () => {
  it('parses the tool output', () => {
    const models = parseFrameControllerModels(FIXTURE);
    expect(models.hands.right?.asset).toBe('right.glb');
    expect(models.hands.right?.animations.map((a) => a.kind).sort()).toEqual([
      'button',
      'button',
      'stick',
      'visibility',
    ]);
  });

  it('rejects other files and versions', () => {
    expect(() => parseFrameControllerModels({})).toThrow();
    expect(() =>
      parseFrameControllerModels({ ...FIXTURE, version: 99 }),
    ).toThrow(/version 99/);
    expect(() => parseFrameControllerModels({ ...FIXTURE, hands: {} })).toThrow(
      /no controller models/,
    );
  });

  it('builds a valve-frame profile pointing at the models', () => {
    const profile = frameProfileWithModels(FIXTURE);
    const right = profile.layouts.right as any;
    expect(right.assetPath).toBe('right.glb');
    expect(right.frameModel).toBe(FIXTURE.hands.right);
    expect(right.components['a-button'].gamepadIndices.button).toBe(4);
    for (const c of Object.values(right.components) as any[]) {
      expect(c.visualResponses).toEqual({});
    }
    expect(profile.profileId).toBe('valve-frame');
  });
});

describe('loadFrameControllerModels', () => {
  it('fetches the models and registers them with their visual', async () => {
    const urls: string[] = [];
    const fetchImpl = (async (url: string) => {
      urls.push(url);
      return { ok: true, json: async () => FIXTURE };
    }) as unknown as typeof fetch;
    await loadFrameControllerModels('/frame-models/', fetchImpl);
    expect(urls).toEqual(['/frame-models/frame-controller-models.json']);

    const config = loadInputProfile(source('right'));
    expect(config.visualClass).toBe(FrameControllerVisual);
    expect(config.assetPath).toBe('/frame-models/right.glb');
  });

  it('reports HTTP errors', async () => {
    const fetchImpl = (async () => ({
      ok: false,
      status: 404,
      statusText: 'Not Found',
    })) as unknown as typeof fetch;
    await expect(loadFrameControllerModels('/x', fetchImpl)).rejects.toThrow(
      /404/,
    );
    expect(loadInputProfile(source('right')).visualClass).toBeUndefined();
  });
});

describe('FrameControllerVisual', () => {
  it('places the model at its grip offset and hides rest-hidden nodes', () => {
    const v = visual('right', pad());
    const inner = v.model.children[0];
    expectPose(inner, FIXTURE.hands.right!.gripFromModel!);
    expect(node(v, 'a_touch_dot').visible).toBe(false);
    expect(node(v, 'body').visible).toBe(true);
  });

  it('replays the trigger, A button and touch dot', () => {
    const gamepad = pad();
    const v = visual('right', gamepad);
    const trigger = animation('button', 'trigger');
    const a = animation('button', 'button_a');

    v.update();
    expectPose(node(v, 'trigger'), trigger.rest);
    expectPose(node(v, 'button_a'), a.rest);

    gamepad.buttons[0].value = 1;
    gamepad.buttons[4] = { pressed: true, touched: true, value: 1 };
    v.update();
    expectPose(node(v, 'trigger'), trigger.pressed);
    expectPose(node(v, 'button_a'), a.pressed);
    expect(node(v, 'a_touch_dot').visible).toBe(true);

    gamepad.buttons[0].value = 0.5;
    v.update();
    const half = node(v, 'trigger').quaternion.angleTo(
      new Quaternion(
        ...(trigger.rest.orientation as [number, number, number, number]),
      ),
    );
    expect(half).toBeGreaterThan(0.15);
    expect(half).toBeLessThan(0.2);
  });

  it('tilts the stick per direction, with gamepad y pointing down', () => {
    const gamepad = pad();
    const v = visual('right', gamepad);
    const stick = animation('stick', 'stick');

    gamepad.axes[2] = 1;
    v.update();
    expectPose(node(v, 'stick'), stick.right);

    gamepad.axes[2] = 0;
    gamepad.axes[3] = -1; // Pushed forward.
    v.update();
    expectPose(node(v, 'stick'), stick.up);

    gamepad.axes[3] = 1;
    v.update();
    expectPose(node(v, 'stick'), stick.down);

    gamepad.axes[3] = 0;
    v.update();
    expectPose(node(v, 'stick'), stick.rest);
  });

  it('skips animations for components the hand does not have', () => {
    const gamepad = pad();
    const v = visual('left', gamepad);
    gamepad.buttons[4] = { pressed: true, touched: true, value: 1 };
    v.update();
    // Slot 4 is the mirrored X on the left; the left layout has no
    // a-button, so the node keeps its asset pose.
    expect(node(v, 'button_a').position.length()).toBe(0);
    // Shared components still animate.
    gamepad.buttons[0].value = 1;
    v.update();
    expect(node(v, 'trigger').quaternion.x).toBeGreaterThan(0.17);
  });
});

describe('controller adapter', () => {
  const loader: XRAssetLoader = {
    async loadGLTF() {
      return { scene: asset() } as Awaited<
        ReturnType<XRAssetLoader['loadGLTF']>
      >;
    },
  };

  function adapter() {
    return new XRControllerVisualAdapter(
      new Group(),
      'right',
      true,
      AnimatedController,
      new Scene(),
      new PerspectiveCamera(),
      loader,
    );
  }

  async function settle() {
    await new Promise((resolve) => setTimeout(resolve, 0));
  }

  it('uses the profile visual for Frame controllers only', async () => {
    registerFrameControllerModels(FIXTURE, '/m');
    const a = adapter();
    a.connect(source('right'));
    await settle();
    expect(a.visual).toBeInstanceOf(FrameControllerVisual);

    const b = adapter();
    b.connect({
      profiles: ['oculus-touch-v3'],
      handedness: 'right',
      gamepad: pad(),
    } as unknown as XRInputSource);
    await settle();
    expect(b.visual).toBeInstanceOf(AnimatedController);
  });

  it('keeps an app-chosen visual', async () => {
    registerFrameControllerModels(FIXTURE, '/m');
    const a = adapter();
    a.updateVisualImplementation(AnimatedController);
    a.connect(source('right'));
    await settle();
    expect(a.visual).toBeInstanceOf(AnimatedController);
  });

  it('drops a Frame visual that finishes loading after the app switches', async () => {
    registerFrameControllerModels(FIXTURE, '/m');
    const space = new Group();
    const a = new XRControllerVisualAdapter(
      space,
      'right',
      true,
      AnimatedController,
      new Scene(),
      new PerspectiveCamera(),
      loader,
    );
    a.connect(source('right'));
    a.updateVisualImplementation(AnimatedController);
    await settle();
    expect(a.visual).toBeInstanceOf(AnimatedController);
    expect(space.children).toEqual([a.visual!.model]);
  });

  it('does not reuse a cached visual across model directories', async () => {
    registerFrameControllerModels(FIXTURE, '/one');
    const a = adapter();
    a.connect(source('right'));
    await settle();
    registerFrameControllerModels(FIXTURE, '/two');
    const b = adapter();
    b.connect(source('right'));
    await settle();
    expect(b.visual).toBeInstanceOf(FrameControllerVisual);
    expect(b.visual).not.toBe(a.visual);
  });
});

describe('registerFrameControllerModels', () => {
  it('resolves model URLs against the page for relative bases', () => {
    registerFrameControllerModels(FIXTURE, 'frame-models/');
    expect(loadInputProfile(source('left')).assetPath).toBe(
      'frame-models/left.glb',
    );
    registerFrameControllerModels(FIXTURE, 'https://cdn.test/m');
    expect(loadInputProfile(source('right')).assetPath).toBe(
      'https://cdn.test/m/right.glb',
    );
  });

  it('keeps the default visual for a hand without a model', () => {
    registerFrameControllerModels(
      { ...FIXTURE, hands: { right: FIXTURE.hands.right } },
      '/m',
    );
    expect(loadInputProfile(source('right')).visualClass).toBe(
      FrameControllerVisual,
    );
    const left = loadInputProfile(source('left'));
    expect(left.visualClass).toBeUndefined();
    expect(left.assetPath).toMatch(/generic-trigger-squeeze-thumbstick/);
  });
});

/** A hand-made model with awkward names, nesting and a rotated stick. */
describe('FrameControllerVisual with a hand-made model', () => {
  const restQ = new Quaternion().setFromAxisAngle(
    new Vector3(0, 1, 0),
    Math.PI / 6,
  );
  const tilt = (axis: Vector3, deg: number) =>
    new Quaternion().setFromAxisAngle(axis, (deg * Math.PI) / 180);
  const X = new Vector3(1, 0, 0);
  const Z = new Vector3(0, 0, 1);
  const pose = (q: Quaternion, p = [0, 0.01, 0]): FramePose => ({
    position: p as [number, number, number],
    orientation: [q.x, q.y, q.z, q.w],
  });
  // Full deflection is the rest orientation followed by a local tilt.
  const right = restQ.clone().multiply(tilt(Z, -15));
  const up = restQ.clone().multiply(tilt(X, -15));

  const models: FrameControllerModels = {
    ...FIXTURE,
    hands: {
      right: {
        ...FIXTURE.hands.right!,
        nodeNames: ['stick.top', 'a touch'],
        visibleAtRest: { 'a touch': true },
        animations: [
          {
            kind: 'stick',
            node: 'stick.top',
            component: 'xr-standard-thumbstick',
            rest: pose(restQ),
            right: pose(right),
            up: pose(up),
            // Left and down never reached: mirrored from right and up.
            left: null,
            down: null,
            confidence: 1,
          },
          {
            kind: 'button',
            node: 'a touch',
            component: 'a-button',
            property: 'touched',
            rest: pose(new Quaternion(), [0, 0, 0]),
            pressed: pose(new Quaternion(), [0, 0.002, 0]),
            confidence: 1,
          },
        ],
      },
    },
  };

  function build(gamepad: Pad) {
    // As GLTFLoader leaves it: sanitized names, a collision suffix, the
    // original name in userData, and the stick nested under a parent.
    const scene = new Group();
    const parent = new Object3D();
    parent.position.set(0.1, 0, 0);
    scene.add(parent);
    const decoy = new Object3D();
    decoy.name = 'stick_top';
    decoy.userData.name = 'stick_top';
    const stick = new Object3D();
    stick.name = 'stick_top_1';
    stick.userData.name = 'stick.top';
    parent.add(decoy, stick);
    const touch = new Object3D();
    touch.name = 'a_touch';
    touch.userData.name = 'a touch';
    scene.add(touch);

    const v = new FrameControllerVisual(
      new Scene(),
      new PerspectiveCamera(),
      scene,
      frameProfileWithModels(models).layouts.right!,
    );
    v.init();
    v.connect(source('right', gamepad), true);
    return { v, stick, decoy, touch };
  }

  const expectQ = (o: Object3D, q: Quaternion) =>
    expect(o.quaternion.angleTo(q)).toBeLessThan(1e-3);

  it('finds nodes by their original glTF names', () => {
    const gamepad = pad();
    const { v, stick, decoy } = build(gamepad);
    gamepad.axes[2] = 1;
    v.update();
    expectQ(stick, right);
    expect(decoy.quaternion.equals(new Quaternion())).toBe(true);
  });

  it('applies tilts in the node frame for every direction', () => {
    const gamepad = pad();
    const { v, stick } = build(gamepad);

    gamepad.axes[2] = 1;
    v.update();
    expectQ(stick, right);

    gamepad.axes[2] = -1; // Mirrored from right.
    v.update();
    expectQ(stick, restQ.clone().multiply(tilt(Z, 15)));

    gamepad.axes[2] = 0;
    gamepad.axes[3] = -1;
    v.update();
    expectQ(stick, up);

    gamepad.axes[3] = 1; // Mirrored from up.
    v.update();
    expectQ(stick, restQ.clone().multiply(tilt(X, 15)));

    gamepad.axes[2] = 0.5;
    gamepad.axes[3] = 0;
    v.update();
    expectQ(stick, restQ.clone().multiply(tilt(Z, -7.5)));

    gamepad.axes[2] = 0.7;
    gamepad.axes[3] = -0.7;
    v.update();
    expectQ(
      stick,
      restQ.clone().multiply(tilt(Z, -10.5)).multiply(tilt(X, -10.5)),
    );
    // Local pose: the parent's offset is not baked in.
    expect(stick.position.toArray()).toEqual([0, 0.01, 0]);
  });

  it('drives touch-property buttons from touch', () => {
    const gamepad = pad();
    const { v, touch } = build(gamepad);
    gamepad.buttons[4] = { pressed: false, touched: true, value: 0 };
    v.update();
    expect(touch.position.y).toBeCloseTo(0.002, 6);
    gamepad.buttons[4].touched = false;
    v.update();
    expect(touch.position.y).toBeCloseTo(0, 6);
  });
});

describe('Frame controllers under SteamVR Touch emulation', () => {
  const touch = (handedness: 'left' | 'right', gamepad: Pad = pad()) =>
    ({
      profiles: ['oculus-touch', 'generic-trigger-squeeze-thumbstick'],
      handedness,
      gamepad,
    }) as unknown as XRInputSource;

  it('shows the real models on a Frame browser', () => {
    registerFrameControllerModels(FIXTURE, '/m', { emulation: true });
    const config = loadInputProfile(touch('right'));
    expect(config.visualClass).toBe(FrameControllerVisual);
    expect(config.assetPath).toBe('/m/right.glb');
    // Touch emulation's own gamepad indices.
    expect(config.layout.components['a-button'].gamepadIndices.button).toBe(4);
    expect((config.layout as any).frameModel).toBe(FIXTURE.hands.right);
  });

  it('leaves Touch controllers alone elsewhere', () => {
    registerFrameControllerModels(FIXTURE, '/m', { emulation: false });
    const config = loadInputProfile(touch('right'));
    expect(config.visualClass).toBeUndefined();
    expect(config.assetPath).toBe(
      `${DEFAULT_PROFILES_PATH}/oculus-touch/right.glb`,
    );
  });

  it('keeps the Touch model for a hand without a Frame model', () => {
    registerFrameControllerModels(
      { ...FIXTURE, hands: { right: FIXTURE.hands.right } },
      '/m',
      { emulation: true },
    );
    const left = loadInputProfile(touch('left'));
    expect(left.visualClass).toBeUndefined();
    expect(left.assetPath).toBe(
      `${DEFAULT_PROFILES_PATH}/oculus-touch/left.glb`,
    );
  });

  it('animates the components the emulation exposes', () => {
    const gamepad = pad();
    const v = new FrameControllerVisual(
      new Scene(),
      new PerspectiveCamera(),
      asset(),
      frameEmulationProfileWithModels(FIXTURE, 'oculus-touch').layouts.right!,
    );
    v.init();
    v.connect(touch('right', gamepad), true);
    gamepad.buttons[0].value = 1;
    gamepad.buttons[4] = { pressed: true, touched: true, value: 1 };
    gamepad.axes[2] = 1;
    v.update();
    expectPose(node(v, 'trigger'), animation('button', 'trigger').pressed);
    expectPose(node(v, 'button_a'), animation('button', 'button_a').pressed);
    expectPose(node(v, 'stick'), animation('stick', 'stick').right);
    expect(node(v, 'a_touch_dot').visible).toBe(true);
  });
});
