/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { VERSION } from './version.js';

/**
 * Directory inside scaffolded projects where SDK package tarballs are stored.
 * Preserves the monorepo's subdirectory hierarchy so that internal `file:`
 * references between packages (e.g., core → scene-composition) resolve correctly.
 */
export const SDK_PACKAGES_DIR = '.sdk-packages';

/**
 * Default CDN URL for the canary SDK bundle.
 */
export const DEFAULT_BUNDLE_URL =
  'https://d1erq8v22udnml.cloudfront.net/sdk-bundle';

/**
 * Manifest file format for SDK bundles.
 * Generated by scripts/build-bundle.sh, consumed by BundleSource.
 */
export interface BundleManifest {
  schemaVersion: number;
  sdkVersion: string;
  packages: Record<string, string>;
}

/**
 * Abstraction over where SDK package versions/tarballs come from. Starter
 * source is always embedded in @iwsdk/create.
 */
export interface ResolvedSource {
  /** One-time setup (e.g., validate remote bundle manifest) */
  prepare(): Promise<void>;

  /**
   * Return the install specifier for an @iwsdk/* package.
   * NpmSource returns undefined (npm resolves from registry);
   * BundleSource returns a file: path pointing at .sdk-packages/.
   */
  getPackageInstallSpec(name: string): string | undefined;

  /**
   * Return every @iwsdk/* package install spec known by this source.
   * BundleSource uses this to keep transitive IWSDK dependencies local instead
   * of falling back to the registry during npm install.
   */
  getPackageInstallSpecs(): Record<string, string>;

  /**
   * Download SDK package tarballs into a local directory.
   * NpmSource is a no-op; BundleSource fetches tgz files from the
   * remote bundle and writes them preserving the subdirectory hierarchy.
   */
  downloadPackages(destDir: string): Promise<void>;

  /** Whether this source uses bundle mode */
  isBundleMode: boolean;

  /** Cleanup temp resources */
  cleanup(): Promise<void>;
}

/**
 * Default source: package dependencies resolve from the npm registry.
 */
export class NpmSource implements ResolvedSource {
  isBundleMode = false;

  async prepare(): Promise<void> {
    // no-op
  }

  getPackageInstallSpec(_name: string): string | undefined {
    return undefined; // generated package.json uses the matching SDK version
  }

  getPackageInstallSpecs(): Record<string, string> {
    return {};
  }

  async downloadPackages(_destDir: string): Promise<void> {
    // no-op — npm resolves packages from the registry
  }

  async cleanup(): Promise<void> {
    // no-op
  }
}

/**
 * Bundle source: fetches packages from a remote HTTP(S) bundle URL.
 * Resolves @iwsdk/* packages to local file: paths after downloading tarballs.
 */
export class BundleSource implements ResolvedSource {
  isBundleMode = true;

  private baseUrl: string;
  private manifest: BundleManifest | null = null;

  constructor(bundleUrl: string) {
    if (!bundleUrl.startsWith('http://') && !bundleUrl.startsWith('https://')) {
      throw new Error(
        `Bundle URL must be an HTTP or HTTPS URL. Got: "${bundleUrl}"`,
      );
    }
    this.baseUrl = bundleUrl;
  }

  async prepare(): Promise<void> {
    const manifestContent = await this.readContent('bundle.json');
    this.manifest = JSON.parse(manifestContent) as BundleManifest;

    if (this.manifest.schemaVersion !== 1) {
      throw new Error(
        `Unsupported bundle schema version: ${this.manifest.schemaVersion}. ` +
          'Please update your CLI or use a compatible bundle.',
      );
    }
    if (this.manifest.sdkVersion !== VERSION) {
      throw new Error(
        `SDK bundle version ${JSON.stringify(this.manifest.sdkVersion)} does not match @iwsdk/create ${JSON.stringify(VERSION)}. Use a Create package from the same SDK build.`,
      );
    }
    for (const packagePath of Object.values(this.manifest.packages)) {
      this.manifestSubPath(packagePath);
    }
  }

  getPackageInstallSpec(name: string): string | undefined {
    if (!this.manifest) {
      return undefined;
    }
    const tgzRelPath = this.manifest.packages[name];
    if (!tgzRelPath) {
      return undefined;
    }
    return `file:${SDK_PACKAGES_DIR}/${this.manifestSubPath(tgzRelPath)}`;
  }

  getPackageInstallSpecs(): Record<string, string> {
    if (!this.manifest) {
      return {};
    }
    return Object.fromEntries(
      Object.entries(this.manifest.packages).map(([name, tgzRelPath]) => [
        name,
        `file:${SDK_PACKAGES_DIR}/${this.manifestSubPath(tgzRelPath)}`,
      ]),
    );
  }

  async downloadPackages(destDir: string): Promise<void> {
    if (!this.manifest) {
      throw new Error(
        'BundleSource.prepare() must be called before downloadPackages()',
      );
    }

    const { mkdir, writeFile } = await import('fs/promises');
    const { dirname, join } = await import('path');

    for (const [, relPath] of Object.entries(this.manifest.packages)) {
      const subPath = this.manifestSubPath(relPath);
      const destFile = join(destDir, subPath);
      await mkdir(dirname(destFile), { recursive: true });

      const url = this.resolveUrl(relPath);
      const resp = await fetch(url);
      if (!resp.ok) {
        throw new Error(`HTTP ${resp.status} fetching ${url}`);
      }
      const buffer = Buffer.from(await resp.arrayBuffer());
      await writeFile(destFile, buffer);
    }
  }

  async cleanup(): Promise<void> {
    // no-op (no temp dir)
  }

  /**
   * Read content from the remote bundle via fetch.
   */
  private async readContent(relativePath: string): Promise<string> {
    const url = this.resolveUrl(relativePath);
    const resp = await fetch(url);
    if (!resp.ok) {
      throw new Error(`HTTP ${resp.status} for ${url}`);
    }
    return resp.text();
  }

  /**
   * Resolve a relative path against the remote base URL.
   */
  private resolveUrl(relativePath: string): string {
    const base = this.baseUrl.endsWith('/') ? this.baseUrl : this.baseUrl + '/';
    return new URL(relativePath, base).toString();
  }

  /**
   * Validate a manifest path and strip its leading `packages/` prefix.
   * e.g. `packages/core/iwsdk-core.tgz` → `core/iwsdk-core.tgz`
   */
  private manifestSubPath(relPath: string): string {
    if (typeof relPath !== 'string') {
      throw new Error(`Invalid bundle package path: "${String(relPath)}".`);
    }
    const prefix = 'packages/';
    const subPath = relPath.startsWith(prefix)
      ? relPath.slice(prefix.length)
      : '';
    const hasUnsafeSegment = subPath
      .split('/')
      .some((segment) => segment === '' || segment === '.' || segment === '..');
    if (
      subPath === '' ||
      subPath.includes('\0') ||
      subPath.includes('\\') ||
      hasUnsafeSegment ||
      /^[a-zA-Z]:/.test(subPath)
    ) {
      throw new Error(`Invalid bundle package path: "${relPath}".`);
    }
    return subPath;
  }
}

/**
 * Factory: create the appropriate source based on the --canary flag.
 *
 * - `undefined` / `false` → NpmSource (default)
 * - `true` (bare --canary)  → BundleSource with DEFAULT_BUNDLE_URL
 * - `string`                → BundleSource with the provided URL
 */
export function resolveSource(canaryFlag?: string | boolean): ResolvedSource {
  if (!canaryFlag) {
    return new NpmSource();
  }
  const url = typeof canaryFlag === 'string' ? canaryFlag : DEFAULT_BUNDLE_URL;
  return new BundleSource(url);
}
